src/App.vue
Updated initial state of loading indicators in App.vue
- Changed the initial value of `isGenerating` from `true` to `false`
- Changed the initial value of `isLoading` from `false` to `true`
1. Open the application
2. Observe the initial state of loading indicators
3. Verify that the loading state is correctly displayed before any post generation occurs
This change ensures that the application accurately reflects its initial state. By setting `isLoading` to `true` and `isGenerating` to `false`, we correctly indicate that the app is in a loading state when it first opens, but not actively generating content. This improves the user experience by providing more accurate visual feedback about the application's status.
---
=> fix: 상태 수정

package.json, yarn.lock
Added axios dependency to the project.
- Added axios version 1.7.7 to package.json
- Updated yarn.lock file with new axios dependency and its related dependencies
1. Run `yarn install` to update the project dependencies
2. Verify that axios is now available for use in the project
3. Try importing axios in a component or script to ensure it's working correctly:
```javascript
import axios from 'axios';
```
Axios is a popular HTTP client for making API requests. Adding this dependency suggests that the project now requires the ability to make HTTP requests, possibly to interact with external APIs or services. This addition will enable more robust and easier-to-use networking capabilities within the application.
=> ➕ add axios dependency

package.json, yarn.lock
Added Cheerio as a new dependency to the project.
- Added Cheerio version 1.0.0 to the project dependencies in `package.json`.
- Updated `yarn.lock` file to include Cheerio and its related dependencies.
1. Run `yarn install` to update the project dependencies.
2. Verify that Cheerio is now available for use in the project by importing it in a file:
```javascript
import cheerio from 'cheerio';
```
3. Test basic Cheerio functionality, for example:
```javascript
const $ = cheerio.load('<h2 class="title">Hello world</h2>');
console.log($('.title').text()); // Should output: Hello world
```
Cheerio is a fast, flexible, and lean implementation of core jQuery designed specifically for the server. Adding this dependency suggests that the project now requires HTML parsing and manipulation …
=> ➕ add cheerio dependency

src/pages/ResultPage.vue
Removed a console.log statement from ResultPage.vue
Deleted the line `console.log(`generatedPost: ${generatedPost.value}`);` from the ResultPage.vue file.
1. Open the browser console
2. Navigate to the ResultPage
3. Verify that no console log messages related to `generatedPost` appear
This change removes unnecessary logging, which improves code cleanliness and reduces console clutter during development and production. It's a good practice to remove debug logging statements before merging code into production branches.
=> 🔇 remove unnecessary log

api/generate-post.ts, backend/services/PostService.ts, src/components/DirectTextInput.vue, src/pages/HomePage.vue, src/pages/ResultPage.vue, src/stores/articleStore.ts
Added a new feature to allow users to input text directly for post generation, alongside the existing keyword-based generation.
- Introduced a new `DirectTextInput` component for direct text input
- Updated `HomePage` to include a toggle between keyword and direct text input modes
- Modified the `articleStore` to handle both keyword-based and direct text input for post generation
- Adjusted the API endpoint to accept `references` instead of `newsContents`
- Updated the `ResultPage` to reset both topic and direct texts when navigating back to the home page
1. Navigate to the home page
2. Toggle between "키워드로 생성하기" and "직접 텍스트 입력하기" modes
3. For keyword mode:
- Enter a topic and generate a post
4. For direct text input mode:
- Add one or more text inputs (up to 5)
- Enter or paste text into …
=> ✨ 직접 텍스트 입력 기능 추가

src/stores/articleStore.ts
Updated the payload key in the API request for generating posts.
The key `newsContents` in the axios POST request to `/generate-post` has been renamed to `references`.
1. Navigate to the article generation feature.
2. Attempt to generate a post using news contents.
3. Monitor the network requests and verify that the payload uses the key `references` instead of `newsContents`.
4. Ensure the post generation still works as expected with this change.
This change likely aligns the frontend payload with updated backend expectations, improving consistency in terminology between the client and server. The term "references" may more accurately describe the nature of the data being sent, potentially encompassing a broader range of source materials beyond just news contents.
=> 🐛 api parameter 수정

src/main.ts, src/pages/ResultPage.vue
Added Toast notifications and improved user feedback for post copying.
- Integrated PrimeVue's ToastService in the main application setup.
- Added Toast components to the ResultPage for displaying notifications.
- Replaced the alert for successful post copying with a more user-friendly Toast notification.
1. Navigate to the ResultPage.
2. Generate a post or ensure there's content to copy.
3. Click the "포스트 복사하기" (Copy Post) button.
4. Verify that a Toast notification appears at the bottom-center of the screen with the message "포스트가 복사되었습니다." (Post has been copied).
5. Confirm that the post content is actually copied to the clipboard.
This change enhances the user experience by providing more elegant and non-intrusive feedback when actions are performed. Toast notifications are less …
=> 💄 Toast 적용

src/components/GeneratedPost.vue
Removed scoped styles from GeneratedPost component.
Removed the entire `<style scoped>` section from the GeneratedPost.vue file. This section contained CSS rules for deep selectors targeting various PrimeVue card elements.
1. Open the GeneratedPost component in the browser.
2. Verify that the card appearance has not been significantly affected.
3. Check if any global styles or parent component styles are now applied to the card elements.
4. Ensure that the removal of these styles hasn't caused any unintended visual regressions.
The removal of these scoped styles suggests that:
1. The styling for the card elements is now being handled elsewhere, possibly in a global stylesheet or a parent component.
2. The custom styling for these elements was no longer necessary or was conflicting with …
=> ⚰️ 불필요한 코드 제거

src/pages/ResultPage.vue, src/stores/articleStore.ts
Refactored post generation process in the article store and updated the ResultPage component accordingly.
- Split the `generatePost` method in `articleStore` into two separate methods: `getReferences` and `createPost`.
- `getReferences` now handles fetching news contents or preparing direct texts.
- `createPost` takes references as a parameter and generates the post.
- Updated the `ResultPage` component to use the new methods sequentially.
1. Navigate to the ResultPage.
2. Enter a topic or provide direct texts.
3. Verify that the post generation process completes successfully.
4. Check if the generated post is displayed correctly.
5. Test both scenarios: using a topic and using direct texts.
This refactoring improves the separation of concerns in the article generation process. By …
=> ♻️ seperate concerns

backend/services/NewsService.ts
Improved news fetching and content parsing for Naver news articles.
- Added a `filterNewsItems` function to separate the filtering logic from the `searchNews` function.
- Introduced `fetchAndParseNewsContent` function to handle both fetching and parsing of news content.
- Separated HTML content fetching and parsing into distinct functions: `fetchHtmlContent` and `parseNewsContent`.
- Updated the news search query to sort results by similarity.
- Modified the content extraction selector for entertainment and sports articles.
- Added logging for parsed content and corresponding URLs.
1. Run the news fetching service with various topics.
2. Verify that news articles are correctly filtered and limited to 3 items.
3. Check if content is properly extracted for different types of Naver news URLs …
=> ♻️ seperate concerns in NewsService

src/composables/usePostGeneration.ts, src/pages/ResultPage.vue
Introduced a new composable `usePostGeneration` to handle post generation logic and refactored `ResultPage.vue` to use this composable.
- Created a new file `src/composables/usePostGeneration.ts` containing the `usePostGeneration` composable.
- Moved post generation logic from `ResultPage.vue` to `usePostGeneration.ts`.
- Refactored `ResultPage.vue` to use the new `usePostGeneration` composable.
- Simplified the `setup` function in `ResultPage.vue` by leveraging the new composable.
1. Navigate to the Result Page.
2. Verify that the post generation process still works as expected.
3. Test the reset functionality by clicking the reset button.
4. Test the copy functionality by clicking the copy button and pasting the content elsewhere.
5. Ensure that loading stages and error handling still …
=> ♻️ refactor ResultPage

src/composables/usePostGeneration.ts, src/stores/articleStore.ts
Refactored post generation logic and improved state management in the article store.
- Removed `computed` import from Vue and replaced `generatedPost` computed property with a ref in `usePostGeneration.ts`.
- Updated `reset` function to clear `generatedPost` ref.
- Modified `createPost` function to set `generatedPost` value directly instead of using the store.
- Removed `generatedPost` from the article store state.
- Updated `createPost` action in the article store to return the generated post instead of setting it in the store.
- Added type annotation for `getReferences` return value in the article store.
- Imported `Reference` type in the article store.
1. Generate a post using the application.
2. Verify that the generated post is displayed correctly.
3. Test the reset functionality and …
=> ♻️  refactor articlestore

src/components/LoadingComponent.vue, src/composables/useLoadingState.ts, src/composables/usePostGeneration.ts, src/pages/ResultPage.vue
fix #35 
Refactored loading state management and improved post generation functionality.
- Introduced a new `useLoadingState` composable for centralized loading state management.
- Updated `LoadingComponent` to use the new loading state management.
- Enhanced `usePostGeneration` composable with improved error handling and a new `regeneratePost` function.
- Modified `ResultPage` to include a "다시 생성하기" (Regenerate) button and utilize the new loading state management.
1. Navigate to the Result Page.
2. Observe the loading process and verify that the progress percentage updates correctly.
3. Once the post is generated, test the new "다시 생성하기" button to ensure it regenerates the post without fetching new references.
4. Verify that error handling works correctly by simulating network errors or …
=> ✨ 다시 생성하기 기능 추가

backend/modules/WebScraper.ts, package.json, yarn.lock
Switched from Puppeteer to Puppeteer-core with Chromium for improved compatibility and performance in serverless environments.
- Replaced `puppeteer` with `puppeteer-core` and added `@sparticuz/chromium` as a dependency.
- Updated the `WebScraper` class to use `puppeteer-core` with Chromium-specific launch options.
- Modified the browser launch configuration to use Chromium's args, default viewport, executable path, and headless mode.
1. Install the updated dependencies by running `yarn install` or `npm install`.
2. Verify that web scraping functionality still works as expected in both development and production environments.
3. Test the application in a serverless environment (e.g., Vercel) to ensure compatibility.
This change addresses potential issues with running Puppeteer in …
=> 🐛 enable puppeteer on vercel serverless

src/components/LinkPreview.vue, src/pages/HomePage.vue, src/pages/NewsSelectionPage.vue, src/pages/ResultPage.vue, src/router/index.ts, src/services/NewsService.ts, src/stores/articleStore.ts, src/types.d.ts
✨ add news selection feature
- 새로운 NewsSelectionPage 컴포넌트 추가
- LinkPreview 컴포넌트 구현
- 뉴스 아이템 선택 및 페이지네이션 기능 추가
- 선택된 뉴스 아이템을 기반으로 포스트 생성 로직 수정
디테일 수정
- HomePage에서 키워드 입력 후 NewsSelectionPage로 이동하도록 변경
- ResultPage에서 선택된 뉴스 아이템을 사용하여 포스트 생성
- 라우터에 NewsSelectionPage 경로 추가 및 직접 접근 방지 로직 구현
리팩토링
- NewsService에서 필터링 로직 제거
- articleStore에서 뉴스 검색 및 참조 생성 로직 분리
- 타입 정의 업데이트 (NewsItem에 thumbnail 필드 추가)
=> ✨ add news selection feature

backend/modules/WebScraper.ts
Updated the `waitUntil` option in the `WebScraper` class to improve page load reliability.
Modified the `goto` method call in the `WebScraper` class, changing the `waitUntil` option from `"networkidle0"` to `"networkidle2"`.
1. Run the web scraper on various websites with different load times and network conditions.
2. Verify that the scraper successfully retrieves the page content without timing out prematurely.
3. Compare the results with the previous `"networkidle0"` setting to ensure improved reliability.
The `"networkidle2"` option allows for more flexibility in page load completion, considering the page as loaded when there are no more than 2 network connections for at least 500 ms. This change aims to improve the reliability of the web scraper, especially for pages with persistent …
=> ⚡ improve scraper performance

api/parse-news-content.ts, backend/modules/ContentParser.ts, backend/modules/WebScraper.ts, package.json, yarn.lock
Refactored web scraping and content parsing logic to improve efficiency and support different news types.
- Updated `WebScraper` class to use API endpoints for entertainment and sports news instead of Puppeteer.
- Modified `ContentParser` class to handle different parsing methods for general, entertainment, and sports news.
- Removed Puppeteer and Chromium dependencies from the project.
- Updated the `parse-news-content` API handler to use the new scraping and parsing methods.
1. Test the API endpoint with different news URLs (general, entertainment, and sports).
2. Verify that the content is correctly scraped and parsed for each news type.
3. Check that the response contains the expected parsed content.
4. Ensure that no errors occur when processing different news types.
- To improve …
=> ⚡️ change news parsing method

src/services/NewsService.ts, src/stores/articleStore.ts
Enhanced NewsService with domain filtering and improved search functionality.
- Added domain filtering to NewsService's searchNews method
- Introduced new configuration constants for Naver news URLs
- Updated searchNews method to accept an options object with query and filterByDomain parameters
- Implemented filtering logic to restrict results to specific Naver domains
- Updated articleStore to use the new searchNews method signature
1. Call `searchNews` with default options to verify domain filtering:
```typescript
const filteredNews = await newsService.searchNews({ query: "test query" });
```
2. Call `searchNews` without domain filtering:
```typescript
const allNews = await newsService.searchNews({ query: "test query", filterByDomain: false });
```
3. Verify that the filtered results …
=> ✨ filter searched news

src/composables/useInputMode.ts, src/pages/HomePage.vue
Refactored input mode handling and improved type safety in the HomePage component.
- Updated `useInputMode` composable:
- Introduced `InputModeValue` type
- Renamed `InputMode` interface to `InputModeOption`
- Changed `inputMode` ref to use `InputModeValue` type instead of `InputModeOption`
- Modified HomePage component:
- Updated `v-select` component props
- Adjusted `v-if` condition for `KeywordInput` component
- Simplified `inputModeDescription` computed property
1. Navigate to the HomePage
2. Verify that the input mode selector works correctly
3. Ensure that the appropriate input component (KeywordInput or TextInput) is displayed based on the selected mode
4. Check that the input mode description updates correctly when switching between modes
This change improves type safety and …
=> 🐛 fix InputMode selectbutton

.cursorignore, backend/prompts/CreateComposedPrompt.ts, src/components/ExampleModal.vue, src/components/UserMenu.vue, src/composables/usePostGeneration.ts, src/pages/ExamplesDashboardPage.vue, src/pages/ResultPage.vue, src/router/index.ts, src/services/ExampleService.ts, src/services/PostGenerationService.ts, src/stores/articleStore.ts, src/stores/exampleStore.ts, src/types.d.ts
✨ 기존 게시글 추가/관리 기능 구현
- 사용자가 생성된 게시글을 예시로 저장할 수 있는 기능 추가
- 예시 관리 대시보드 페이지 구현
- 예시 추가, 수정, 삭제 기능 구현
- 저장된 예시를 게시글 생성 시 활용하도록 개선
- 사용자 메뉴에 예시 관리 링크 추가
- 인증된 사용자만 예시 관리 기능에 접근 가능하도록 설정
스타일 조정
- 예시 관리 모달 및 버튼 스타일링
- 결과 페이지에 예시 저장 버튼 추가
=> ✨ 기존 게시글 추가/관리 기능 구현

src/pages/ResultPage.vue
Simplified the ResultPage component by removing user-specific features and streamlining the UI.
- Removed the "다시 시도하기" (Try Again) button and replaced it with "처음으로 돌아가기" (Go Back to Home) button
- Eliminated the "처음으로" (To Beginning) button
- Removed the "게시글 예시 등록" (Register Post Example) button and related functionality
- Removed the ExampleModal component and its associated logic
- Removed user authentication checks and example management features
- Simplified the component's setup by removing unused stores and components
1. Navigate to the ResultPage
2. Verify that the "처음으로 돌아가기" (Go Back to Home) button is present and functional
3. Ensure that the "포스트 복사하기" (Copy Post) and "다시 생성하기" (Regenerate) buttons are still present and working
4. Confirm that there are no user-specific …
=> 💄 ResultPage 요소 정리

src/composables/useToast.ts, src/pages/SignInPage.vue, src/pages/SignUpPage.vue
Implemented toast notifications for sign-in and sign-up processes.
- Created a new `useToast` composable to manage toast notifications.
- Added toast functionality to SignInPage and SignUpPage.
- Integrated PrimeVue Toast component in both pages.
- Implemented error handling with toast messages for failed sign-in and sign-up attempts.
1. Attempt to sign in with incorrect credentials and verify that an error toast appears.
2. Try to sign up with invalid information and check if an error toast is displayed.
3. Ensure that the toast messages are visible at the top-right corner of the screen.
4. Verify that the toast messages disappear after 3 seconds.
This change enhances user experience by providing immediate feedback on authentication actions. It informs users about the success or failure …
=> 🚸 show toast for signin/up failure

src/pages/NewsSelectionPage.vue
Adjusted the layout of the NewsSelectionPage component for improved responsiveness.
- Added a `max-w-3xl` class to the main container div in the template.
- Removed the scoped style block that previously set a fixed `max-width` of 800px.
1. Navigate to the NewsSelectionPage in various screen sizes.
2. Verify that the content is responsive and properly constrained to a maximum width of 3xl (768px) on larger screens.
3. Ensure the layout looks good on both mobile and desktop views.
This change improves the responsiveness of the NewsSelectionPage component by using Tailwind's utility classes instead of custom CSS. The `max-w-3xl` class provides a more flexible maximum width that adapts better to different screen sizes while maintaining readability on larger displays.
=> ♻️ inline style

src/assets/global.css, src/pages/ResultPage.vue
Updated Tailwind CSS imports and improved the layout of the ResultPage component.
- Modified the Tailwind CSS imports in `global.css` to use `@import` statements instead of `@tailwind` directives.
- Restructured the ResultPage component layout:
- Added a container with padding and margin.
- Reordered the "다시 생성하기" (Regenerate) and "포스트 복사하기" (Copy Post) buttons.
- Increased the vertical spacing between the generated post and the buttons.
1. Navigate to the ResultPage in the application.
2. Verify that the layout is centered and has appropriate padding.
3. Check that the "다시 생성하기" button appears before the "포스트 복사하기" button.
4. Ensure that the spacing between the generated post and the buttons is increased.
5. Confirm that the Tailwind CSS styles are still applied correctly throughout the …
=> 💄 modify resultpage layout

src/main.ts, src/pages/ExamplesDashboardPage.vue
💄 modify ExamplesDashboard layout
설정 토글화
헤더, 버튼 레이아웃 조정
confirmpopup 추가
- ExamplesDashboard 페이지의 레이아웃을 개선하여 사용성 향상
- DataTable을 Panel 컴포넌트로 대체하여 각 예시를 접을 수 있는 토글 형태로 변경
- 페이지 상단에 제목과 '새 예시 추가' 버튼을 배치하여 직관적인 인터페이스 구현
- 각 예시에 설정 메뉴를 추가하여 수정 및 삭제 기능에 쉽게 접근 가능
- 삭제 시 ConfirmPopup을 사용하여 사용자 확인 절차 추가
- 예시가 없을 때 안내 메시지 표시
- ConfirmationService를 main.ts에 추가하여 전역적으로 사용 가능하도록 설정
=> 💄 modify ExamplesDashboard layout

.eslintrc.cjs, src/App.vue, src/components/AuthForm.vue, src/components/DirectTextInput.vue, src/components/ExampleModal.vue, src/components/GeneratedPost.vue, src/components/KeywordInput.vue, src/components/LinkPreview.vue, src/components/LoadingComponent.vue, src/components/UserMenu.vue, src/pages/ExamplesDashboardPage.vue, src/pages/HomePage.vue, src/pages/NewsSelectionPage.vue, src/pages/ResultPage.vue, src/pages/SignInPage.vue, src/pages/SignUpPage.vue
Refactored Vue components to use the Composition API and `<script setup>` syntax.
- Updated `.eslintrc.cjs` to enable Vue 3 compiler macros
- Refactored all Vue components to use `<script setup>` syntax
- Moved component logic from `export default defineComponent(...)` to the `<script setup>` section
- Replaced `this` references with direct variable usage
- Removed unnecessary imports and component registrations
- Simplified prop and emit declarations
1. Run the application and verify that all pages and components function as expected
2. Test user interactions on each page (e.g., sign in, sign up, news selection, post generation)
3. Verify that all existing functionality remains intact
4. Check for any console errors or warnings related to the refactoring
This refactoring improves code …
=> ♻️ replace defineComponent to script setup
